### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by jeddy3** [hudochenkov/stylelint-declaration-block-order#3]
LGTM. Great job!

The configuration, tests and structure of the messages seem to be spot on with what we originally discussed in https://github.com/stylelint/stylelint/issues/1500#issuecomment-232919837.

I reckon you're fine to publish to a first version to npm.

Once you've published I'll add it to the plugin list in stylelint's docs and send out a tweet!

**Comment by hudochenkov** [comment]
Thank you for a review!

Published https://www.npmjs.com/package/stylelint-declaration-block-order
